spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      repositories:
        enabled: false
      timeout: 5s
      connect-timeout: 10s
  cache:
    redis:
      time-to-live: ${REDIS_TTL}
