###
POST http://localhost:8080/api/room
Content-Type: application/json

{"username": ""}

###
GET http://localhost:8080/api/log?room_code=d8835&username=jisu

###
POST http://localhost:8080/api/log
Content-Type: application/json

{"room_code":"", "username": "", "amount": 10000, "memo":  ""}

###
POST http://localhost:8080/api/log
Content-Type: application/json

{"room_code":"", "username": "", "amount": 10000}