name: CI

on: push

jobs:
  build:
    runs-on:
      - self-hosted
      - rpi4
    environment: env test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Test with Gradle Wrapper
        run: ./gradlew test

      - name: Github Environment Test
        run: ${{ secrets.MY_TEST_SECRET }} > /home/zeus/github-env-test.log
