name: CI

on: push

jobs:
  build:
    runs-on: rpi4
    environment: env test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Gradle Wrapper
        run: ./gradlew test

      - name: Github Environment Test
        run: echo ${{ secrets.MY_TEST_SECRET }} > /home/zeus/github-env-test.log
