name: Deploy to home server

on:
  workflow_run:
    workflows: ["Java Build with Gradle"]
    types:
      - completed

jobs:

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: build-jar
          path: build/libs/

      - name: Copy JAR to remote server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          target: '~/workspace/tmp/'
          source: 'build/libs/*.jar'

      - name: SSH and run commands on remote server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script: |
            echo "deploy success" > ~/workspace/tmp/success.log
            echo "deploy success"
